# Generated by Django 3.2.9 on 2021-12-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccounts',
            name='email_address',
            field=models.EmailField(max_length=40, unique=True),
        ),
    ]
