# Generated by Django 3.2.9 on 2021-12-12 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fooddata', '0002_alter_useraccounts_email_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foods',
            old_name='monousaturated_fat',
            new_name='monounsaturated_fat',
        ),
    ]
