# Generated by Django 3.2.9 on 2021-12-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddata', '0003_rename_monousaturated_fat_foods_monounsaturated_fat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccounts',
            name='current_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useraccounts',
            name='currently_logged_in',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useraccounts',
            name='date_account_created',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useraccounts',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useraccounts',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useraccounts',
            name='last_logged_in',
            field=models.DateField(blank=True, null=True),
        ),
    ]
