# Generated by Django 3.2.9 on 2021-12-12 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fooddata', '0004_auto_20211212_1706'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Foods',
            new_name='Food',
        ),
        migrations.RenameModel(
            old_name='UserAccounts',
            new_name='UserAccount',
        ),
    ]
