# Generated by Django 3.2.9 on 2021-12-13 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddata', '0006_auto_20211212_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='date_account_created',
        ),
        migrations.AddField(
            model_name='userdata',
            name='bmi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
