# Generated by Django 3.2.9 on 2022-01-26 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fooddata', '0010_rename_accounts_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
